# Generated by Django 6.0.5 on 2026-05-08 16:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_id', models.UUIDField()),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
